name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload to GitHub Packages
        run: |
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "Uploading version: $POM_VERSION"
          
          curl -X PUT \
            -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            -H "Content-Type: application/java-archive" \
            --data-binary @target/novo-cnpj-validator-$POM_VERSION.jar \
            "https://maven.pkg.github.com/eliaschacon/novocnpjvalidator/io/github/eliaschacon/novo-cnpj-validator/$POM_VERSION/novo-cnpj-validator-$POM_VERSION.jar"
          
          curl -X PUT \
            -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            -H "Content-Type: application/xml" \
            --data-binary @pom.xml \
            "https://maven.pkg.github.com/eliaschacon/novocnpjvalidator/io/github/eliaschacon/novo-cnpj-validator/$POM_VERSION/novo-cnpj-validator-$POM_VERSION.pom"